### ISSUE TITLE
Questions about the training and testing process.

### ISSUE THREAD

**Issue by xindeng98** [LIA-DiTella/DiffUDF#1]
Thank you for your contributions！
I have some questions regarding the training and testing process of the model. It appears that your process is somewhat similar to CAP-UDF in that you fit each scene and reconstruct it. However, in your fitting process, you utilize the SDF values. These SDF values need to be calculated based on the GT mesh. This dependency on the GT mesh might introduce data leakage.

**Comment by miguef98** [comment]
Thanks for your question and interest!

While CAP-UDF and our method may appear similar, they have distinct differences. CAP-UDF focuses primarily on point-cloud reconstruction. In contrast, our work aligns with research on neural implicit representations as an alternative to discrete representations like triangle meshes, point clouds, or voxels. This approach has been arguably more common in recent studies, such as those by Park et al. (2019), Clemot et al. (2023), and Novello et al. (2022), which supervise the distance field.

We use CAP-UDF as a baseline because it was, to our knowledge, the most competent open surface implicit neural representation at the time. Additionally, techniques like CAP-UDF's complex sampling strategy for point-cloud reconstruction or SIREN's regularization term are not orthogonal to our work and could potentially be adapted to DUDF.

Hope this clarifies things! If you have any more questions or need further details, feel free to ask.

**Comment by xindeng98** [comment]
Thanks for your explanation, I understand that your work focuses on exploring the representation of implicit fields rather than obtaining implicit fields from point clouds. Your theoretical description is rigorous and intuitive, but I think you should explain in the paper how your experimental setup is different from cap-udf.

**Comment by xubaixinxbx** [comment]
Thank you for the authors' clarification. I understand that there are three groups of points: surface points, domain points, and near-surface points, as described in Section 4.1. It appears that only domain points require manual distance calculation using a tree-based search algorithm[1]. Meanwhile, the ground truth mesh may not be necessary in this step. for real scans, we approximate the distance based on the point cloud.

[1] Qian-Yi Zhou, Jaesik Park, and Vladlen Koltun. Open3D: A modern library for 3D data processing.
